import '@/styles/app.scss'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Nav from './components/layout/Nav';
import Image from 'next/image';
import bgRadial from '@/assets/img/bg-radial.png'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'MantaSwap by MantaDAO',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <div className="fixed left-0 bottom-0 w-[60vw] h-[50vw] opacity-10">
        <div className="radial-circle w-[1200px] h-[1200px] absolute top-0 right-0"></div>
      </div>
        <Nav />
        {children}
        </body>
    </html>
  )
}
